2FA
===
Guenther Brunthaler
v2026.36.1

How to set up time- or event-based 2-factor authentication in Linux.

The easiest way to setup 2FA for Linux seems to be the "Google Authenticator" PAM component. (PAM is a Linux framework for extending authentication methods using plug-in modules.)


Installing Google Authenticator
-------------------------------

Google Authenticator consists of a PAM plugin module as well as a userspace application.

The module performs the actual authentication checks when logging in, and the application is used to set up 2FA for the current user.

There is an official Debian package which can be installed, and the module installed by it is also fine for being used.

Unfortunately, the userspace application has a security flaw, and needs to be patched in order to generate a safe shared authentication key.

The build and installation instructions are more detailed for Debian-based systems than for other ones.

If you are not sure whether this applies to your system, run the following commands in a terminal windows for probing your system type:

----
case `command -v apt dpkg dpkg-deb | wc -l` in
3) echo This is a Debian-based system;;
*) echo This is NOT a Debian-based system
esac
----

Linux distributions *not* based on Debian
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You are on your own for now.


Debian-based Linux distributions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Use the following instructions if your system's package management is based on 'dpkg'.

. Die Tools installieren, die nötig sind um das neue Zeugs überhaupt
bauen zu können bauen.
+
--
Doch noch bevor du irgendwas anders machst, stelle sicher dass nicht
die C Shell läuft, sondern eine POSIX-Shell wie die bash oder ksh!

\Z. B. mittels

----
$ exec bash -l; exec -l ksh; exec -l ash; echo 'NO shell found!!!'
----

Als nächstes benötigen wir "fakeroot". Das brauchen wir um als
nicht-privilegierter User überhaupt Pakete bauen zu können.

Installiere dieses Paket daher, falls es noch nicht installiert ist:

----
$ command -v fakeroot || sudo \
  apt-get -o APT::Get::Mark-Auto=1 install fakeroot
----

Führe die folgenden Schritte dann als normaler User durch. Also nicht
als "root".

. Erzeuge dir irgendwo ein Arbeitsverzeichnis
+
--
----
$ tmpdir-shell # Create a tmpfs-based temporary directory and go there.
----
--

. Installieren der zum Bauen benötigten Tools (Compiler usw)
+
--
Das erledigt man am einfachsten mit einem Abhängigkeitspaket, welches
als Abhängigkeit alle benötigten Tools hat.

Vorteil: Nach dem erfolgreichen Bauen des eigentlichen Programms kann
man dieses Paket wieder entfernen, da die Compiler etc. dann nicht mehr
gebraucht werden.

Als nächstes lege die folgende Textdatei an:

----
cat << 'EOF' > t
Package: google-authenticator-bdeps-20230509$
Version: 1.0$
Architecture: all$
Maintainer: None <none@nowhere.invalid>$
Depends: git, c-compiler, autoconf, automake, libtool, libpam0g-dev, $
libqrencode-dev, dpkg-dev, alien, fakeroot$
Provides: meta-03e4d2fe9e3b11e88c3db827$
Section: misc$
Priority: optional$
Multi-Arch: foreign$
Description: Build dependencies for fixing the flawed original $
google-authenticator userspace application$
EOF
----

Nicht über die "$" wundern - die habe ich dran gefügt weil die Zeilen
für die Mail zu lange waren und von mir daher umgebrochen wurden.

Nun entfernen wir diese Umbrüche wieder um die benötigte Originaldatei
herzustellen:

----
mkdir deps
mkdir deps/DEBIAN
cat t | sed 's/ [$]$/ /; t; s/[$]$/|/' | tr -d '\n' | tr '|' '\n' \
  > deps/DEBIAN/control
----

Du kannst dir das Ergebnis ansehen - die Paketbeschreibungsdatei sollte
nun wieder frei von Umbrüchen sein:

----
$ cat deps/DEBIAN/control
----

Damit sind die Erfordernisse für den Bau eines Abhängigkeitspakets
erfüllt - so ein Paket enthält nicht mehr als eine DEBIAN/control Datei.

Erzeugen des Abhängigkeitspakets:

----
$ fakeroot dpkg-deb -b deps
----

Das erzeugt das Abhängigkeitspaket unter dem Namen "deps.deb".

Aufräumen:

----
$ rm -r deps t
----

Nun installieren wir das neue Abhängigkeitspaket:

----
$ sudo dpkg -i deps.deb
----

Das dpkg wird nun jammern, dass die im Paket angeforderten
Abhängigkeiten nicht erfüllt sind. Mit dem folgenden Befehl bringen wir
sie dazu, nachinstalliert zu werden:

----
$ sudo apt-get install --fix-broken
----

Da das Abhängigkeitspaket nun installiert ist, können wir die
Paketdatei wieder löschen:

----
$ rm deps.deb
----

Nun sollten alle benötigten Tools und Utilitys installiert und das
Arbeitsverzeichnis wieder leer sein.
--
--

. Die Quelltexte vom Google Authenticator besorgen
+
--
----
repourl='https://github.com/google/google-authenticator-libpam.git'
commit=366ace3e5849d0d259915ddff22c8ec55e40b3ad
git init
git remote add origin "${repourl:?}"
git fetch -q --depth=1 origin "${commit:?}"
git reset --hard FETCH_HEAD
----

Die Quelltexte sollten nun im aktuellen Verzeichnis sein.

Als nächstes korrigieren wir einen Mangel, der die Verwendung potenziell minderwertiger Zufallszahlen erlaubt:

----
$ sed -i 's|/dev/urandom|/dev/random|g' src/google-authenticator.c
----
--

. Configure-Script erzeugen
+
--
Das für dem Bau benötigte ./configure-Script wird normalerweise nie in
git eingecheckt, da sie erzeugt werden kann.

Statt dessen wird für diesen Zweck normalerweise ein Script beigelegt,
häufig unter dem Namen "autogen.sh". In diesem Fall heißt es anders:

----
$ sh bootstrap.sh
----

Diese Script sollte einige Sekunden herum werkeln und am Ende ein
./configure Script erzeugen.

Wir können es nun benutzen.
--

. Konfigurieren des Builds
+
--
----
./configure CFLAGS="-D NDEBUG -pipe -O2 -mtune=native" \
   LDFLAGS="-s -Wl,-O1,--as-needed,--hash-style=gnu"
----

Das sollte uns ein Makefile erzeugen.
--

. Den eigentlichen Build durchführen
+
--
Als erstes ermitteln wir die Anzahl paralleler Build-Prozesse anhand
der vorhandenen CPU-Cores:

----
$ n=`nproc || echo 1` && n=`expr $n + 1` && echo $n
----

Dann bauen wir:

----
$ make -l$n -j$n
----

Damit sollte alles gebaut sein.

Nur dann weiter machen, wenn dies nicht mit irgend einem Fehler
versagte!
--

. Ein Staging-Directory erstellen
+
--
Wir installieren die Dateien nicht direkt an ihren Bestimmungsort,
sondern erst in ein Staging-Directory:

----
$ make install DESTDIR="$PWD"/stage
----

Dabei installiert "make" ein bisschen zu viel in dieses Directory. Wir
löschen den unnötigen Schrott wieder:

----
$ find stage -name '*.la' -exec rm -- {} +
----

Der Inhalt des Staging-Directories ist nun dazu bereit, installiert zu
werden.

Man könnte es nun einfach rüberkopieren. Aber so etwas ist ja ein
Pfusch und macht Probleme wenn man das Zeugs später wieder
deinstallieren wollen! Etwa wenn es irgendwann ein neueres
fehlerbereinigtes Original-Debian-Paket geben sollte.

Daher bauen wir auch hierfür ein Debian-Paket! Nun allerdings eines das
auch Dateien enthält.
--

. Installationspaket bauen
+
--
Wir beginnen auch hier mit der Beschreibungsdatei.

Ich habe sie ebenfalls für die E-Mail umgebrochen und mit '$' am
Zeilenende abgesichert, damit du es hier aus der Mail problemlos ins
Terminal-Fenster kopieren kannst:

----
cat << 'EOF' > t
Package: libpam-google-authenticator$
Source: google-authenticator$
Version: 20230505-1.09-g366ace3$
Architecture: @ARCH@$
Maintainer: None <none@nowhere.invalid>$
Depends: libc6 (>= 2.25), libpam0g (>= 0.99.7.1), libqrencode4, $
oathtool$
Provides: meta-03e4d2fe9e3b11e88c3db827$
Section: admin$
Priority: optional$
Homepage: https://github.com/google/google-authenticator/$
Description: Two-step verification$
 The Google Authenticator project includes implementations of one-time$
 passcode generators for several mobile platforms, as well as a$
 pluggable authentication module (PAM). One-time passcodes are $
generated$
 using open standards developed by the Initiative for Open$
 Authentication (OATH) (which is unrelated to OAuth).$
 .$
 These implementations support the HMAC-Based One-time Password (HOTP)$
 algorithm specified in RFC 4226 and the Time-based One-time Password$
 (TOTP) algorithm currently in draft.$
EOF
----

Nun wie schon beim ersten Paket die "$" entfernen und eetwaige Umbrüche
rückgängig machen:

----
mkdir stage/DEBIAN
cat t | sed 's/ [$]$/ /; t; s/[$]$/|/' | tr -d '\n' | tr '|' '\n' \
  > stage/DEBIAN/control
----

Allerdings enthält die Datei auch noch einen Platzhalter für die
Architektur des aktuellen Geräts, welchen wir durch die des lokalen
Geräts ersetzen müssen:

----
eval `dpkg-architecture | grep ^DEB_HOST_ARCH=`; echo $DEB_HOST_ARCH
sed -i "s/@ARCH@/$DEB_HOST_ARCH/" stage/DEBIAN/control
----

Auch hier das Ergebnis kontrollieren ob es richtig aussieht:

----
$ cat stage/DEBIAN/control
----

Und bauen dann das Paket:

----
$ fakeroot dpkg-deb -b stage
----

Das Paket hat nun den langweiligen Namen "stage.deb". Wir benennen es
nun in einen besser geeigneten Namen um, da wir das Paket danach auch
aufheben können um es auf anderen Rechnern zu installieren:

----
$ dpkg-name stage.deb
----

Dies benennt die Datei in
"libpam-google-authenticator_1.09-20230505-g366ace3_armhf.deb" um.
Zumindest wenn du sie ebenfalls auf einem Raspi baust.

Danach noch aufräumen:

----
$ rm -r stage t
----
--

. Installationspaket installieren
+
--
Nun installieren wir das neue Paket sauber mit dem Paketmanager:

----
$ sudo dpkg -i libpam-google-authenticator_*.deb
----

Nur falls er sich über fehlende Libraries aufregt den folgenden Befehl
absetzen um diese zu installieren:

----
$ sudo apt-get install --fix-broken
----

Damit sind wir fertig!

Du kannst nun die neue *.deb-Datei irgendwo hin weg sichern, falls du
es auch auf andere Debian-Rechner mit derselben Hardware-Architektur
installieren willst.
--

. RPM erzeugen
+
--
Als nächstes sind wir lustig und versuchen das Paket in ein
Fedora-Paket umzuwandeln damit man es auch dort installieren kann:

----
$ fakeroot alien --to-rpm libpam-google-authenticator_*.deb
----

Das erzeugt falls man das ganze am Raspi tat eine Datei

----
libpam-google-authenticator-1.09_20230505-1.armhf.rpm
----

die sich theoretisch auf einer Fedora-Distro mit derselben
Hardware-Architektur installieren lassen sollte.

Ob es auch tatsächlich klappt ist eine andere Frage. So könnte die
Installation z. B. versagen weil abhängige Pakete unter Fedora anders
heißen.

Da du deine Fedora-Rechner aber vermutlich nicht unter armhf sondern
amd64 betreibst, wirst du die obigen Bau-Instruktionen wohl auf einem
Debian-basierten amd64-Rechner durchführen müssen.

Zumindest wenn du sie 1:1 ohne Anpassungen durchführen willst. Weil ich
habe keinen Schimmer mehr (lange ist es her) wie man unter Red Hat
Pakete baut oder installiert.

Wenn du kein Debian, Ubuntu oder dergleichen für amd64 hast, mache das
ganze am besten mit einer Debian Live-DVD in einer VM.

Gib der VM nur genug Speicher - oder eine virtuelle Disk die du als
riesigen Swap-File anlegst - damit sich alles im RAM der Live-DVD
ausgeht ohne dass du ein Dateisystem einrichten musst.

Die gebauten Installationspakete für Debian und Fedora (siehe weiter
unten) sicherst du dann mit `scp` aus der VM bevor die diese wieder
herunter fährst.
--

. Aufräumen
+
--
Nun kann das Arbeitsverzeichnis wieder gelöscht werden, da alles
erledigt ist.

Falls man das heruntergeladene git-Repository nicht verlieren will,
kann man es irgendwo anders hin klonen:

----
$ git clone --bare . /path/to/elswhere/google-authenticator-libpam.git
----

Danach alles vorhin Angelegte wieder löschen:

----
$ exit # Leave and destroy temporary directory created by `tmpdir-shell`
----
--

. Build-Tools wieder loswerden
+
--
Dieser Schritt ist *optional*. Da das Paket nun gebaut und installiert
ist, benötigen wir die ganzen anfangs installierten Build-Tools nicht
mehr.

Du kannst sie daher wieder deinstallieren um Platz zu sparen.

Zuerst das Abhängigkeits-Paket:

----
$ sudo apt-get purge google-authenticator-bdeps-20230509
----

Danach alle nun nicht mehr benötigten Abhängigkeiten deinstallieren:

----
$ sudo apt-get autoremove --purge
----
--

. Fertig
+
--
Das war's!

Ich hoffe, es funktioniert alles tatsächlich so wie ich es hier
beschrieben habe.
--


PAM configuration
-----------------

If there are files `/etc/pam.d/$SERVICE`, then those files contain rules of the line format:

....
type control module-path module-arguments
....

Otherwise, the file `/etc/pam/pam.conf` contains rules of the following line format:

....
service type control module-path module-arguments
....

Both formats are equivalent; in the first case the missing `service` field is assumed to be the same as `$SERVICE` (the configuration file name).

The PAM man page frequently used the term "stacked", but fails to actually explain what that means.

Which is: PAM-Entries for the same service (such as "login") and type (such as "auth") are considered to be a sequence ("stack") of rules rather than independent individual rules.

The rules within a stack are executed in the same relative order as they appear in the PAM configuration files.

If some rule is said to "stop processing the remaining rules of the stack", this only affects the rules within the current stack (say "auth") but not rules from other stacks (such as "session").

All rules of a service are considered for execution in the same order in which they are present in their configuration file, no matter to which stack every line belongs.

However, the outcome of previous rules determines whether such a rule is actually executed. If a previous rule stopped execution of the remaining rules for the same stack, further rules of this stack will not be executed.


Enabling TOTP-1FA
~~~~~~~~~~~~~~~~~

This allows authentication to all services using TOTP only on Debian-style PAM setups (but only if the account has been configured with a TOTP password using the `google-authenticator` utility): Insert the following line

----
auth    sufficient                      /usr/local/lib/security/pam_google_authenticator.so nullok
----

somewhere before the first `auth`-line in `/etc/pam.d/common-auth`.

For instance, the affected section of that file might look like this after the insertion:

----
# here are the per-package modules (the "Primary" block)
auth    sufficient                      pam_google_authenticator.so nullok
auth    [success=2 default=ignore]      pam_unix.so nullok
auth    [success=1 default=ignore]      pam_ldap.so use_first_pass
# here's the fallback if no module succeeds
----

The `nullok` means that using TOTP is optional and the normal authentication (such as password login) will be used if no TOTP code has been setup yet. This is useful if not all users are using TOTP logins.


Enabling TOTP-2FA
~~~~~~~~~~~~~~~~~

This requires both a TOTP code and the normal login password in order for the user to successfully authenticate.

The PAM configuration is the same as for TOTP-1FA, except that `sufficient` must be replaced by `required`.

Also, if no logins without 2FA shall be possible, remove the `nullok` option. Be warned though that no logins will be possible for accounts which have not already run `google-authenticator` in order to set up 2FA credentials.

Also note that it is also possible to add the `pam_google_authenticator.so` rule to a specific `/etc/pam.d/*` file rather than to `common-auth`. In this case, only a particular service will make use of 1FA or 2FA, while the settings in `common-auth` are shared among all service types (`ssh`, `login`, `su`, etc.)


Testing the installation
------------------------

If everything is correct, the following commands should work like this:

----
$ command -v google-authenticator
/usr/local/bin/google-authenticator

$ grep /dev/urandom /usr/local/bin/google-authenticator || echo NOT FOUND
NOT FOUND

$ grep /dev/random /usr/local/bin/google-authenticator || echo NOT FOUND
Binary file /usr/local/bin/google-authenticator matches
----

Man kann das Ding nun benutzen, genau wie in der man-Page erläutert.

Hier als Beispiel wie man eine zeitbasierte Authentifikation erstellt:

----
$ host=`hostname` user=`id -un` && echo "$user@$host from $host" # Default for --label and --issuer
$ host=demohost user=demouser

$ google-authenticator --label="${user:?}@${host:?}" --issuer "$host" --no-confirm --time-based --disallow-reuse --force --qr-mode=UTF8_INVERSE --rate-limit=3 --rate-time=30 --window-size=17 --emergency-codes=0
                                             
  █▀▀▀▀▀█ █ ▄█  ▀  ▀█▄ ▄█ ▀█▄▀ ▄▀█▄ █▀▀▀▀▀█  
  █ ███ █ ▀▄▄▀█▀▄ █ ▄▀█ ▀  ▀█▀▄▀▀▄▄ █ ███ █  
  █ ▀▀▀ █ ▀  ▄▀▀█  █▄  ▄ █▄  ▀▀ ▀▀▄ █ ▀▀▀ █  
  ▀▀▀▀▀▀▀ ▀▄▀ █ █ █ █▄▀ █▄█▄█ █ ▀▄▀ ▀▀▀▀▀▀▀  
  █▄▄█▀█▀█▀▄  █▀▀█▀▀▄▀ ▄ █▀ ▄▄ ▀██▄▀▄▄█▄▀▀▀  
     █▀█▀ ▀▀██▀▄█▀██▀▄▀▀▄█  ▄▀ ▄▀▄▀▀█ ▄█  ▄  
  ▄▀▀▄ ▄▀▄▀ █▀▀▄ ▀ ▀▄█▀▀▄ ▄ ▀▀█  ▄█ █▄▄   ▀  
   ▄▀ █ ▀   █▀▀█ █   ▄  ▄ ▄▀ ▄▀▀█▀ ▄█▀▄▄█▄█  
  █ █ ▄▄▀▀  █▀▄▄▀▄█  █▄ ██▀▄   █▄ ▄▄  ▄  ▀   
  ▄▀█ ▄▄▀██████▄▄▀ ▄▄▀▄▀██  ▄▀ ▀▀▀▄ ▀ █ █▄▀  
  ▄█ █▀▀▀▀█ ▄▀█▀▀█▀ ▄▀▀▀▀  ██▄▄▄▀█ █▀▄▄▄▄    
  ▄█▄█▀█▀▄▀ ▄██▀▄▄██▄  ▀▀▀▄▀▄▀ ▄ ▄ ▀▀  █▀ ▄  
  ▄ █ ▄█▀▀▀██▀ ▄▀▄ ▄▄▀  ▄█▀▄▄█▄  ▀▄ ▀▄█▀▄▀▄  
  ▄    █▀▀█▄█▀▀▀█ ▀ ▄▀▀▀   ▀▀█ ▀█▀▄▄ ▄▄█▄▄█  
  █▀█▄  ▀█▀▄  █▄▀▄▀█   ███▀   █▄▄█▄▄  ▄▀▄▄█  
  ██▄▄ █▀███▀▀▄█▀▀▄ ██▄▀█▄▀▄▄▀ ▀▄▀▄ ▀▄ ▀█ ▀  
  ▀▀   ▀▀ ▄ ▀█ ▄▄█ ▀▀█▀▄ █▄▀█▀▀▄▄██▀▀▀███ ▀  
  █▀▀▀▀▀█ █  ▀█   ██▀▄ ▄██▄ █▀  ▄▄█ ▀ █▀ ▄▄  
  █ ███ █ █  █▄▀█▀ ▀▀█ ▀ ▀▀█▀█▄▀▄▀▀█▀▀▀  ▄▀  
  █ ▀▀▀ █    ▀▀ ██▄█ █▀ ▀  ▀█▀  ▄▄▀█ ▀█▄▄ █  
  ▀▀▀▀▀▀▀ ▀▀ ▀▀▀ ▀▀▀▀ ▀ ▀▀▀▀ ▀   ▀▀ ▀▀▀      
                                             
Your new secret key is: E5ECZXUGQTALTQAW6WJOSZBDDIDYFA7E
Your verification code for code 1 is 492058
Your emergency scratch codes are:

$ cat ~/.google_authenticator
E5ECZXUGQTALTQAW6WJOSZBDDIDYFA7E
" RATE_LIMIT 3 30
" WINDOW_SIZE 17
" DISALLOW_REUSE
" TOTP_AUTH
----

Das obige Kommando setzt voraus dass das Terminal hellen Text auf schwarzem Hintergrund verwendet. Verwendet es hingegen dunklen Text auf weißen Hintergrund, muss eine der Optionen zu `--qr-mode=UTF8` geändert werden.

Den obigen QR-Code kann man am Handy direkt in die FreeOTP-App einscannen, mit dem QR-Code Icon in dieser App.

Decodiert ergibt der QR-Code folgenden Text im Falle des obigen Beispiels:

----
otpauth://totp/demouser@demohost?secret=TKUPW2ZFPD6VGBFIIO5YZSLK2J4JABY5&issuer=demohost
----

Der Issuer (`--issuer`) ist der Rechner für den der Code zum Einloggen gedacht ist. Default ist der Hostname des aktuellen Rechners; normalerweise sollte das gut genug sein.

Das Label (`--label`) hingegen ist das was in der FreeOTP-App als Eintragstitel angezeigt wird. Default ist user@hostname wobei "user" natürlich der aufrufende User ist und "hostname" der Name des eigenen Rechners. Unter der Annahme dass man ein Login für diesen Rechner erzeugen will, passt das normalerweise auch.

Das Label setzt sich aus "issuer:account" zusammen, wobei der "issuer:"-Teil im Label jedoch optional ist und weggelassen werden darf. Die obige URI macht von diesem Weglassen Gebrauch.

Wenn der "issuer:"-Teil jedoch benutzt wird, muss das darin enthaltene ":" als "%3A" URI-encoded werden.

Neben den oben gezeigten Parametern sind noch weitere definiert, etwa für den Hash-Algorithmus. Die Parameter-Werte "SHA1", 30 Sekunden, 6 Ziffern sind jedoch der Default und dürfen daher weg gelassen werden.

Das Secret muss zumindest 128 Bit lang sein, darf jedoch auch länger sein. Es darf *keine* Padding-Zeichen ("=") am Ende enthalten. Wenn der Base-32 Encoder diese ausgibt, müssen sie entfernt werden bevor das Secret in die URL eingefügt wird.

Secret ersetzen
---------------

Dem vom Google Authenticator erzeugten Secret sollte man nicht trauen, da es mit möglicherweise geringer Entropie generiert wurde. Es ist daher sicherer es nach der Erzeugung durch ein selbst erzeugtes Secret zu ersetzen.

Der Google Authenticator codiert das binäre Secret als Base-32 mit dem folgenden Alphabet: `ABCDEFGHIJKLMNOPQRSTUVWXYZ234567` ("`A`"-"`Z`", "`2`"-"`9`"). Dieses Alphabet ist in RFC 4648 definiert und auch das "coreutils"-Utility "`base32`" verwendet es.

Das TOTP/HOTP Secret sind 32 Zeichen aus dem Base-32 Alphabet. Das sind 160 Bit bzw. 20 Octets ("Bytes").

In früheren Versionen war das anders und 128 Bit bzw. 16 Bytes wurden damals zu einem Secret mit 26 Zeichen aus dem Base-32 Alphabets formatiert. Die OTP-Apps akzeptieren offensichtlich unterschiedliche Längen des Secrets und füllen es falls nötig durch Anhängen von `0`-Bits auf eine Anzahl kompletter Bytes auf.

Das bedeutet, dass man sich eigene hochwertigere Base-32 Secrets mit folgendem Befehl erzeugen kann:

----
tmpdir-shell # Create a tmpfs-based temporary directory and go there.

outchars=32

octets=`expr \( $outchars \* 5 + 8 - 1 \) / 8`

nl=`printf '\n:'` && nl=${nl%:}

keygen-octets-by-harvesting-entropy ${octets:?} | base32 | cut -c 1-$outchars > secret.psw

chmod +w ~/.google_authenticator

sed -i "1{r secret.psw${nl:?}d}" ~/.google_authenticator

chmod -w ~/.google_authenticator

qr="otpauth://totp/${user:?}@${host:?}?secret=`cat secret.psw`&issuer=$host"

qrencode -t UTF8 "$qr"

echo "QR-encoded string: $qr"

exit # Leave and destroy temporary directory created by `tmpdir-shell`
----

Der Verification Code ist 6-stellig, als Hash kommt SHA-1 zum Einsatz.


QR-Code anzeigen
----------------

So zeigt man den QR-Code für den aktuellen Account an:

----
host=`hostname` user=`id -un`

qr="otpauth://totp/${user:?}@${host:?}?secret=`head -n 1 ~/.google_authenticator`&issuer=$host"

qrencode -t UTF8 "$qr"

echo "QR-encoded string: $qr"
----


QR-URIs om Batch erzeugen
-------------------------

Eine Datei `logins.txt` im aktuellen Verzeichnis anlegen. Jede Zeile soll die Form user@host haben, was zugleich der Eintragstitel in einer OTP-App sein wird.

Die folgenden Kommandos erzeugen eine URI für jeden Eintrag, der - in einen QR-Code umgewandelt - von einer OTP App eingescannt werden kann, um einen Eintrag zu erzeugen.

----
tmpdir-shell # Create a tmpfs-based temporary directory and go there.

#echo "`id -un`@`hostname`" > logins.txt # Uncomment to generate demo file

outchars=32 show_qr_code=false
octets=`expr \( $outchars \* 5 + 8 - 1 \) / 8`
nl=`printf '\n:'` && nl=${nl%:}
while read account
do
	issuer=${account#*"@"}
	keygen-octets-by-harvesting-entropy ${octets:?} | base32 | cut -c 1-$outchars > secret.psw
	qr="otpauth://totp/${account:?}?secret=`cat secret.psw`&issuer=$issuer"
	if $show_qr_code
	then
		echo && qrencode -t UTF8 "$qr" # Uncomment to display QR-Codes in output
	fi
	echo
	echo "$qr"
done < logins.txt | tee output.txt | less --quit-if-one-screen

echo 'Enter 'exit' to delete this directory and its contents!'
echo 'Before you do so, make sure 'output.txt' and 'logins.txt''
echo 'have been saved somewhere else if you want to keep them.'

#exit # Leave and destroy temporary directory created by `tmpdir-shell`
----

Wenn `show_qr_code=true` geändert wird, werden die QR-Code in die Ausgabe eingefügt.

Die Ausgabe befindet sich danach in der Datei `output.txt`, wird davor aber mit "less" am Bildschirm angezeigt.


Secret aus URI lokal setzen
---------------------------

Wenn man viele TOTP-URIs im Batch erzeugt hat, möchte man sie danach auf auf lokalen Accounts installieren.

Die folgenden Befehle fragen nach einer URI oder dem Pfadnamen einer Grafikdatei welche den QR-Code einer URI enthält. Das enthaltene Secret wird extrahiert und in die Datei `~/.google_authenticator` geschrieben. Danach kann man sich dann mit einer PIN einloggen welche von einer Authenticator-App stammt, welche mit demselben QR-Code initialisiert wurde.

----
clear && echo "{ base64 -d << EOF | gzip -dc | sh -e; } 5<& 0"
gzip -9c << 'EOF' | base64; echo EOF
prefix='otpauth://totp/'
clear
while :
do
	echo "This is `id -un`@`hostname` (`hostname -f`)"
	echo
	echo "Please paste either an TOTP configurtion URI or the path to an"
	echo "image file containing a QR-encoded TOTP URI."
	printf %s "Your input [press Return at the end]? "
	if reply= && IFS= read reply <& 5
	then
		if test -z "$reply"
		then
			echo "Empty input. Assuming user wants to abort."
			uri=
			break
		fi
		case $reply in
			"$prefix"*) uri=$reply; break;;
			*)
				if test -f "$reply"
				then
					uri=`zbarimg -- "$reply" 2> /dev/null || :`
					uri=${uri#*:} # Strip "QR-Code:"
					case $reply in
						"$prefix"*) break
					esac
				else
					echo "Invalid QR-code image pathname." >& 2
					echo >& 2
					continue
				fi
		esac
	fi
	echo; echo "Invalid input."; echo
done
while :
do
	test "$uri" || break
	uri=${uri#"$prefix"} # Strip prefix.
	secret=`
		printf '%s\n' "$uri"	| sed 's/.*[?&]secret=\([A-Z2-9]\{26,\}\).*/\1/; t; d'
	`
	if test -z "$secret"
	then
		echo "No valid URI containing a secret. Aborting." >& 2
		false || break
	fi
	if test ! -f ~/.google_authenticator
	then
		google-authenticator --no-confirm --time-based --disallow-reuse --force --qr-mode=none --rate-limit=3 --rate-time=30 --window-size=17 --emergency-codes=0 > /dev/null 2>& 1 || break
	fi
	chmod +w ~/.google_authenticator
	sed -i "1s/.*/$secret/" ~/.google_authenticator
	chmod -w ~/.google_authenticator
	echo "Successfully replaced TOTP secret in user account with that from URI."
	break	
done
rc=$?; unset reply secret uri prefix
test $rc = 0 && unset rc || unset rc && false
EOF
----

Dieser Befehl tut zunächst einmal noch gar nichts, sondern verpackt die enthaltenen Befehle lediglich in einen sehr viel kürzerne Befehl welchen man danach einfacher in mehrere Terminals kopieren und dort ausführen kann, da er noch zur Gänze auf den Bildschirm passt.


TOTP-Einmalcode anzeigen
------------------------

Dies zeigt jenen 6-stelligen Code an, der zum Einloggen in den aktuellen Account via TOTP nötig ist:

----
$ head -n 1 ~/.google_authenticator | oathtool --totp --base32 @/dev/stdin
----

Das dazu benötigte Utility `oathtool` kann man mit einem Paket gleichen Namens installieren.


TOTP-Einmalcode verifizieren
----------------------------

Man kann eine TOTP auch als Mensch nutzen, um sicher zu stellen dass ein Kommunikationspartner derjenige ist welcher er zu sein behauptet.

Das Kommando zum Verifizieren ist dasselbe wie zum Erzeugen, nur dass die zu prüfende PIN als zusätzlicher Kommandozeilen-Parameter dran gefügt wird.

`oathtool` zeigt dann `0` an wenn die PIN gültig ist, und eine Fehlermeldung andernfalls. Der Exit-Code des Kommandos gibt ebenfalls darüber Auskunft, ob die PIN korrekt war.


Emergency scratch codes
-----------------------

Wenn man nicht `--emergency-codes=0` angibt um dies zu unterdrücken, generiert der Google Authenticator bei der Erzeugen einer neuen Datei `~/.google_authenticator` mehrere sogenannte "Emergency Scratch Codes".

Das sind einfach Zufallszahlen, welche man anstatt einer gültigen TOTP-PIN ebenfalls eingeben kann um sich anzumelden. Durch diese Benutzung wird der Code "verbraucht" und aus der `~/.google_authenticator` gelöscht.

Die Generierung solcher Codes macht nur dann einen Sinn, wenn man sie sich auf Papier ausdruckt und an einem sicheren Ort aufbewahrt (z. B. einem Safe).

Dann kann man sich für eine begrenzte Anzahl an Situationen auch dann einloggen, wenn man keine OTP-App zur Verfügung hat oder diese nicht funktioniert. Etwa weil das Handy kaputt oder gestohlen wurde.

Man kann sie aber natürlich auch in einem Passwort-Manager oder sonst wo deponieren wo man sie finden kann; es muss nicht unbedingt ausgedruckt sein.

Normalerweise braucht man solche Codes nicht. Und wenn man mehrere Geräte besitzt wo dieselben TOTP-URIs eingerichtet sind, reichen die in der Regel als Backup.


TOTP vs. HOTP
-------------

Einige Authenticator Apps unterstützen neben TOTP auch HOTP. Das ist dasselbe Prinzip, nur wird die aktuelle Uhrzeit durch einen Zähler ersetzt.

Vorteil von HOTP ist dass es auch dann korrekt funktioniert wenn entweder auf dem Rechner wo man sich einloggen will oder auf dem Gerät wo die OTP-App läuft die Uhrzeit falsch oder sehr ungenau ist.

Nachteil ist dass sowohl Client als auch Server denselben Zählerwert irgendwo speichern muss.

HOTP funktioniert daher üblicherweise nur ein einzelner Account mit einer einzigen App auf einem einzigen Gerät zusammen arbeitet.

Denn wenn man mehrere Apps auf verschiedenen Geräten betreibt - wie sollten diese ihre Zählerwerte mit einander synchronisieren?

Man könnte den Zähler natürlich in der Cloud speichern, aber dann das höhlt die Einfachheit des Systems empfindlich aus.

Da kann man statt dem HOTP gleich ein langes Passwort nehmen.

Sinn würde HOTP vor allem für Logins in ein Preboot-Environment auf Rechnern ohne batteriegestützte Echtzeituhr haben.

Den Counter-Wert speichern diese Rechner an besten in einer winzigen Partition welche nur einen Sektor umfasst. So braucht kein Dateisystem gemountet zu werden um den Counter zu lesen oder zu aktualisieren.
