Aktuelles Verzeichnis mit rdiff-backup sichern
==============================================
v2026.68

Oft hat man das Problem, Dateien im aktuellen Verzeichnis schnell und effizient irgendwo anders hin backuppen zu wollen.

Dies kann man mit `rdiff-backup` sehr effektiv erledigen, welches durch seine Verwendung von Rückwärts-Deltas sehr platzsparend arbeitet.

Allerdings ist es eine Herausforerung, die "man"-Page zu studieren und die ganzen Optionen zu erforschen, wenn man es gerade eilig hat.

Das folgende Script kann hier helfen.

Um es zu entpacken, zuerst die nachfolgende Kommandozeile ausführen, welche noch keine Dateien erzeugt sondern die Scripte nur anzeigt:

----
$ base64 -d << EOF | zcat |less # sh -e
H4sIAKeirmkCA31STW+bQBA9e37FBKMgO1pwrFiVmpD2UKnqpe2hR0vJsgxmZWARu26dyspvz7Am
Co7cctidrzfz3jJT/EoNddJRjtkT2lJ2D5nsKDMNWfy9XCyX8fXNh/gGlHR4j/U22+HdHUZp/0Uw
vcAk001iS4Cpr1/Fy9UKLDkUBK6TLUaOrMPwE6a4wMMBSZUGg3UQLtYBFlJXlF8EeH+JywgXALZT
aQy5dWk/TGRSbXetBahNTunRgz8lo3BDzrTOYpFXGtmC3MBESUsYsoe6gcmkmKEHRpVmEgXDbHR7
y4n8NaFM3bLiY7Q6KdeN6qimxg0Y/Y8sCmH136HFfMaiKibRS91rBxOyUjG3hsCWunD4SPu2w/DH
z1/fvn9Bgdd96cdH8K/W5booBtUY9uPgKKk3vaYhd8CB+YyH+vcWGISfA1yzPxGC9qra5SQ2lcn4
F21EL94T9+86Ttv3mLOlFryQs2xmOGYgRNvpxgnrpOMuWv0POhJy0iQIeROCI5D2pF6jvBkB+PUD
VXIvvNp7mjBa0XfqRgs7n8eyPzK59Rfz4Mv0h6tbvpL4uTJqO2fzeRhzpvFJzzgZb2rCfrzJs4eS
pZvuCa6wD2iX6KYwydDgLapMU+gNHL1h4gtmhZLjlwMAAA==
EOF
----

Danach einfach die Zeichenkette "`less #`" aus der 1. obigen Zeile entfernen und das Kommando erneut ausführen.

Dadurch werden 3 Dateien erzeugt:

* Das eigentliche Backup-Script. Es wird als `./mkbu` aufgerufen.
* Datei `rdiff-exclude-globs`. Sie enthält Dateinamen-Muster von auszuschließende Dateien welche Shell-Joker wie `*` und `?` enthalten.
* Datei `rdiff-excludes`. Sie enthält exakte Pfadenamen von auszuschließenden Dateien.

Alle 3 Dateien müssen vor der Verwendung editiert werden.

In `mkbu` müssen die Zeilen welche mit `src=` und `dst=` beginnen angepasst werden. Sie legen die absoluten oder relativen Pfade fest, welcher Verzeichnisbaum gesichert werden soll, und in welches Backup-Verzeichnis. Letzteres wird automatisch erzeugt falls es noch nicht existiert.

Aus den `*exclude*` Dateien sollten die Beispiel-Exklusionen entfernt und gegen echte ersetzt werden. Werden keinerlei Exklusionen benötigt, können beide Dateien auch leer sein.

Ein paar Anmerkungen zu `rdiff-excludes`:

* Pfadnamen die mit `./` beginnen sind relativ zum Quellverzeichnis.
* Pfadnamen die mit `/` beginnen sind absolut.
* Pfadnamen die mit nichts davon beginnen passen auf jede Datei, deren Pfadnamen von irgend einem der Unterverzeichnisse aus betrachtet mit diesem Pfadnamen enden.

Wenn das `./mkbu`-Kommando ohne Argumente aufgerufen wird, machte es ein (weiteres) Backup.

* Die Option `-f` listet alle Dateien auf die im letzten Backup vorhanden sind.

* Die Option `-l` listet alle vorhandenen Backups (automatisch vergebener Name und Datum) auf. Dies ist sehr schnell.

* Die Option `-i` listet auf, welche vollen und inkrementellen Backups vorhanden sind und wie viel Speicherplatz im Backup-Verzeichnis sie belegen. Dies ist viel aufwändiger als "-i" und entsprechend langsamer.
